### PR TITLE
Add app icon in line with GNOME HIG

### PR DESCRIPTION
**Pull request by drpetrikov**
I've added an icon i made, it looks like a polaroid photo of a cloud on a blue sky, with a bent corner, and a symbolic version, to replace the previous generic project emblem design.

### CODE REVIEW

**Comment by blissd** [comment]
Thank you very much for putting in the time and effort to create a new icon for Fotema. I do agree that Fotema's current icon isn't great and should be replaced. However, I don't think the icon you've made quite works for me and my aesthetic preferences. This isn't a reflection on your work, which looks well done, but on my own subjective tastes. 

What do I want from Fotema's app icon? I don't know, but I'll know it when I see it.

**Comment by drpetrikov** [comment]
@blissd no problem! but if you want to, you can send me inspirations or sketches for an icon and i'll make it. i love your app so much, i've been looking for a libadwaita photos app for so long, it's a godsend

**Comment by blissd** [comment]
Thank you, that is kind offer and your comments have really made my day.

**Comment by blissd** [comment]
I've raised an[ issue to capture my thought on icons](https://github.com/blissd/fotema/issues/88).

**Pull request closed without merging**
